README.md
config/horizon.env
config/stellar-core.cfg
image/Dockerfile.horizon
image/Dockerfile.stellar-core
image/docker-compose.yml
image/init.sh
image/stellar-core.cfg

this is an example on how to setup a local private testnet with a single core + horizon setup.
includes:
1. README with tutorial
1. docker + compose + init.sh scripts to guide you

add image/ dir with local testnet docker setup

---

image/Dockerfile.friendbot
image/Dockerfile.stellar-archivist

reduces from 1.68 Gb to 400 Mb

delete glide cache to reduce image size

---

image/Dockerfile.laboratory
image/docker-compose.yml
image/laboratory/opt/laboratory/configure_network.sh

Reduced the docker image of laboratory from 248MB > 125 MB :smile:

Reduced docker image size

---

image/Dockerfile.laboratory

Once I removed the WORKDIR statement I forgot to change the final path :smile:

fix laboratory path

---

image/Dockerfile.laboratory
image/docker-compose.yml
image/laboratory/opt/laboratory/configure_network.sh
image/laboratory/opt/laboratory/init.sh

The ENV variables passed by docker-compose don't get passed while building the "dist" folder, so now I edit the final app.js file when starting the container
The final image was uploaded to dockerhub under kinecosystem/laboratory:1

fix and pull laboratory image

---

deploy/stellar-livenet/horizon/horizon.env
image/docker-compose.yml

required for curating database, otherwise it fills up
see this for more information:
https://www.stellar.org/developers/horizon/reference/admin.html#managing-storage-for-historical-data

add HISTORY_RETENTION_COUNT config to horizon examples

---

deploy/kik-testnet/datadog-agent/etc/datadog-agent/conf.d/json_check.md
deploy/kik-testnet/datadog-agent/etc/datadog-agent/conf.d/json_check.yaml

Added stellar core and horizon metrics, so the user should uncomment whichever metrics he is interested in

More stellar metrics

---

deploy/kik-testnet/datadog-agent/etc/datadog-agent/conf.d/json_check.yaml

Just fixed the jsonpath since I accidentally replaced "5m.rate" with "5_min_rate" for the entire file instead of only core.
Also changed the horizon url to localhost:80/metrics

fix jsonpath

---

deploy/terraform/horizon.tf.j2
deploy/terraform/modules/horizon/elb.tf

also route53 health check evaulates elb health check using alias resource

activate horizon-health-check with elb + route53

---

deploy/ansible/inventory/example.yml
deploy/ansible/inventory/localhost.yml
deploy/ansible/playbooks/example.yml
deploy/ansible/playbooks/group_vars/example/kms.yaml
deploy/ansible/playbooks/roles/get-parameter/tasks/main.yml
deploy/ansible/playbooks/roles/put-parameter/tasks/main.yml
deploy/terraform/.gitignore
deploy/terraform/kms.tf.j2
deploy/terraform/ssh-key.tf.j2
deploy/terraform/state.tf.j2

this is instead of using the default key
allows more granular control on access to sensitive information

terraform + ansible use  custom AWS SSM KMS CMK per network

---

deploy/terraform/horizon.tf.j2
deploy/terraform/modules/horizon/ec2.tf
deploy/terraform/modules/stellar-core/ec2.tf
deploy/terraform/modules/stellar-core/route53.tf
deploy/terraform/modules/stellar-core/vars.tf
deploy/terraform/stellar-core.tf.j2
deploy/terraform/tasks.py

from horizon source security group

stellar-core allows ingress control port 11626 only from horizon

---

deploy/ansible/playbooks/roles/horizon-setup/templates/docker-compose.yml.j2
images/docker-compose.yml
images/dockerfiles/Dockerfile.horizon-bin
images/dockerfiles/horizon-build.sh

available from https://github.com/kinecosystem/go/pull/4

Setup number of max connections to horizon db

---

deploy/terraform/README.md
deploy/terraform/modules/horizon/rds.tf
deploy/terraform/modules/stellar-core/rds.tf

in addition some small readability README updates

use 'default' subnet group name for rds in terraform

---

deploy/ansible/playbooks/roles/datadog-horizon/meta/main.yaml
deploy/ansible/playbooks/roles/datadog-stellar-core/meta/main.yml

should be easier to measure them now

update horizon + core metrics for datadog

---

deploy/ansible/playbooks/roles/datadog-horizon/meta/main.yaml
deploy/ansible/playbooks/roles/datadog-json-check/files/json_check.py
deploy/ansible/playbooks/roles/datadog-stellar-core/meta/main.yml

this fixes the wrong metric types in our datadog dashboards

add metric types ansible datadog horizon + core roles

---

tests/go/src/github.com/kinecosystem/core/Pipfile
tests/go/src/github.com/kinecosystem/core/Pipfile.lock
tests/go/src/github.com/kinecosystem/core/images/docker-compose.yml
tests/go/src/github.com/kinecosystem/core/tasks.py

for end-to-end tests. currently it only launches a single core + horizon network

add initial invoke and docker support for launching test network

---

tests/go/src/github.com/kinecosystem/core/.gitignore
tests/go/src/github.com/kinecosystem/core/images/Dockerfile.horizon
tests/go/src/github.com/kinecosystem/core/images/Dockerfile.horizon-build
tests/go/src/github.com/kinecosystem/core/images/Dockerfile.stellar-core
tests/go/src/github.com/kinecosystem/core/images/Dockerfile.stellar-core-build
tests/go/src/github.com/kinecosystem/core/images/copy/stellar-core-build/build.sh
tests/go/src/github.com/kinecosystem/core/images/docker-compose.yml
tests/go/src/github.com/kinecosystem/core/tasks.py

now invoke can build core + horizon and then start a network
hopefully all in a single command

add invoke tasks for building core and horizon

---

deploy/instructions.txt
deploy/terraform/tasks.py
federation-nodes/deploy/ansible/playbooks/group_vars/example/stellar-core.cfg.yml
federation-nodes/deploy/ansible/playbooks/roles/stellar-core/templates/stellar-core.cfg.j2

@oryband:
1. I added a sort of manual. it lists many of the pitfalls and a step-by-step for some of the non obvious things. its not perfect, but for now it'll do.
2. I also added some modified terraform/config files for the federation use case. its deliberately placed in a different folder (under federation nodes).

added some federation-specific deploy scripts and guide

---

deploy/ansible/playbooks/roles/horizon-health-check/templates/docker-compose.yml.j2
deploy/ansible/playbooks/roles/horizon-nginx-proxy/templates/docker-compose.yml.j2
deploy/ansible/playbooks/roles/stellar-core/templates/docker-compose.yml.j2
images/dockerfiles/horizon-telegraf/README.md
images/dockerfiles/stellar-core-telegraf/README.md
images/dockerfiles/telegraf-datadog-forwarder/README.md

@avi-kik please approve this config change: it tells docker to restart after a machine reboot and not just after an application failure.

change docker restart policy

---

tests/python/test_tx_order_by_fee.py
tests/python/test_tx_order_by_whitelist.py
tests/python/test_tx_priority_for_whitelist_holder.py

Added 2 tests:
1. Testing tx priority in the ledger based on the fee
2. Testing that the whitelisted has the highest priority level

Add more tests

---

tests/python/helpers.py
tests/python/test_multiple_cores.py

multi kin cores tests

---

deploy/terraform/modules/horizon/rds.tf
deploy/terraform/modules/stellar-core/rds.tf

@avi-kik  please approve this tiny change. updating the version to the latest safe one.

update db version to latest safe one

---

deploy/ansible/playbooks/group_vars/example/stellar-core.cfg.yml
deploy/ansible/playbooks/roles/stellar-core/templates/stellar-core.cfg.j2

Add whitelist account configuration to the deploy script

add whitelist config to stellar core deploy script

---

images/docker-compose.yml
images/dockerfiles/Dockerfile.friendbot
images/volumes/friendbot/opt/friendbot/friendbot.cfg.envsubst
tasks.py

also, invoke can build any other golang apps along with horizon

add friendbot support for build, dockerhub and local test network in invoke

---

tasks.py
tests/python/helpers.py
tests/python/test_base_reserve.py
tests/python/test_multiple_cores.py
tests/python/test_tx_order_by_fee.py
tests/python/test_tx_order_by_whitelist.py
tests/python/test_tx_priority_for_whitelist_holder.py
tests/python/test_whitelist_affected_on_next_ledger.py

add core end-to-end tests task to invoke

---

deploy/ansible/playbooks/group_vars/example/horizon.yml
deploy/ansible/playbooks/horizon.yml
deploy/ansible/playbooks/roles/apt-get-upgrade/tasks/main.yml
deploy/ansible/playbooks/roles/horizon-setup/templates/docker-compose.yml.j2

also add new apt-get-upgrade role

updates to horizon ops

---

images/dockerfiles/Dockerfile.stellar-core

current version is 16.04 which soon will be EOL

update core docker image to be based on ubuntu 18.04 LTS

---

images/dockerfiles/Dockerfile.stellar-core-build

instead of 16.04 (soon to be EOL)

Core build image is based on Ubuntu 18.04

---

images/dockerfiles/Dockerfile.horizon

this new command is similar to the way horizon was started before
and was introduced post 0.16.0

add CMD ["serve"] to horizon Dockerfile

---

images/dockerfiles/Dockerfile.stellar-core-build

Reverts kinecosystem/blockchain-ops#149

Revert "revert core building back to ubuntu 16 after 18 failed"

---

images/dockerfiles/stellar-core-build/build.sh

not required for production use

remove core debug build flags

---

apps/docker-quickstart/pubnet/core/etc/stellar-core.cfg

add the kik core to the quickstart config

---

images/dockerfiles/telegraf-datadog-forwarder-testnet/telegraf.conf.tmpl

Hey Ory,
Fixed some configuration.

Fixed endpoints for testnet telelgraf forwarder

---

images/dockerfiles/telegraf-datadog-forwarder-testnet/input-exec/calc_ledger_close_time.sh
images/dockerfiles/telegraf-datadog-forwarder-testnet/telegraf.conf.tmpl
images/dockerfiles/telegraf-datadog-forwarder/input-exec/calc_ledger_close_time.sh
images/dockerfiles/telegraf-datadog-forwarder/telegraf.conf.tmpl

turn field into tag in close time metric

---

apps/horizon-health-check/build-and-push.sh
apps/horizon-health-check/main.py
apps/horizon-health-check/tests.py
requirements.txt

checking sync from core current ledger and horizon DB record of the core current ledger is in sync

horizon sync status

---

images/dockerfiles/telegraf-datadog-forwarder-testnet/Dockerfile
images/dockerfiles/telegraf-datadog-forwarder-testnet/build-and-push.sh
images/dockerfiles/telegraf-datadog-forwarder-testnet/input-exec/count_tx_ops.sh
images/dockerfiles/telegraf-datadog-forwarder-testnet/telegraf.conf.tmpl
images/dockerfiles/telegraf-datadog-forwarder/Dockerfile
images/dockerfiles/telegraf-datadog-forwarder/build-and-push.sh
images/dockerfiles/telegraf-datadog-forwarder/input-exec/count_tx_ops.sh
images/dockerfiles/telegraf-datadog-forwarder/telegraf.conf.tmpl

Added New metric to Docker image: Telegraf-Forwarder (Prod and Testnet)
Metric in datadog: "Operations and TXs per Ledger"

Telegraf forwarder new ledger count

---

dashboard/prometheus/README.md

added readme for the Prometheus dashboard

added readme for the Prometheus dashboard

---

tests/python/create.py

adding json output for the create account to support the load test format
optional parameter for the create.py: --json_output
kept backward compatibility

Json output

---

tasks.py

This will help building either our own or Stellar's versions.

add org, repo, dir name parameters for building core and horizon using invoke tasks.py

---

images/dockerfiles/horizon-telegraf/input-exec/check-sysctl.sh
images/dockerfiles/horizon-telegraf/telegraf.conf.tmpl

adding network configuration from sysctl to telegraf checks

adding network configuration from sysctl to telegraf checks

---

images/dockerfiles/Dockerfile.stellar-core
tasks.py

fix broken invoke core build task following #209
